
import { HalalStatus, IngredientDetail } from "../types";

export interface OfflineIngredient {
  id: string;
  names: string[];
  i18nNames?: Record<string, string[]>;
  status: HalalStatus;
  reason: Record<string, string>;
}

// Comprehensive Offline Database for common E-Numbers and Ingredients
export const OFFLINE_DB: OfflineIngredient[] = [
  {
    id: "E120",
    names: [
      "e120", "carmine", "cochineal", "carminic acid", "كارمين", "دودة القرمز", "حشرة القرمز",
      "cochenille", "acide carminique", "karmin", "asam karminat", "karminik asit", "koşinil",
      "karminsäure", "кармин", "карминовая кислота", "кошениль", "کارمائن", "کوچنیل",
      "asid karminik", "কারমাইন", "কোচিনিল", "胭脂红", "胭脂虫红", "胭脂酸", "کارمین", "اسید کارمینیک",
      "carmín", "ácido carmínico", "cochinilla", "कारमाइन", "कोचीनियल", "karmin kislotasi",
      "кармин қышқылы", "кармин кислотасы", "karmîn", "കാർമൈൻ"
    ],
    i18nNames: {
      en: ["carmine", "cochineal", "carminic acid"],
      ar: ["كارمين", "دودة القرمز", "حشرة القرمز"],
      fr: ["cochenille", "acide carminique"],
      id: ["karmin", "asam karminat"],
      tr: ["karminik asit", "koşinil"],
      de: ["karminsäure", "karmin"],
      ru: ["кармин", "карминовая кислота", "кошениль"],
      ur: ["کارمائن", "کوچنیل"],
      ms: ["asid karminik"],
      bn: ["কারমাইন", "কোচিনিল"],
      zh: ["胭脂红", "胭脂虫红", "胭脂酸"],
      fa: ["کارمین", "اسید کارمینیک"],
      es: ["carmín", "ácido carmínico", "cochinilla"],
      hi: ["कारमाइन", "कोचीनियल"],
      uz: ["karmin kislotasi"],
      kk: ["кармин қышқылы"],
      ky: ["кармин кислотасы"],
      ku: ["karmîn"],
      ml: ["കാർമൈൻ"]
    },
    status: HalalStatus.HARAM,
    reason: {
      ar: "مستخرج من حشرة القرمز (الكارمين)، وهو محرم عند معظم المذاهب.",
      en: "Derived from the cochineal insect (Carmine), which is considered Haram by most scholars.",
      fr: "Dérivé de l'insecte cochenille (Carmin), considéré comme Haram par la plupart des savants.",
      id: "Berasal dari serangga cochineal (Karmin), yang dianggap Haram oleh sebagian besar ulama.",
      tr: "Çoğu alim tarafından Haram kabul edilen koşinil böceğinden (Karmin) elde edilir.",
      de: "Gewonnen aus der Cochenilleschildlaus (Karmin), was von den meisten Gelehrten als Haram angesehen wird.",
      ru: "Получено из кошенильного червеца (Кармин), что считается Харамом большинством ученых.",
      ur: "کوچنیل کیڑے (کارمائن) سے ماخوذ، جسے زیادہ تر علماء حرام سمجھتے ہیں۔",
      ms: "Berasal daripada serangga cochineal (Carmine), yang dianggap Haram oleh kebanyakan ulama.",
      bn: "কোচিনিল পোকা (কারমাইন) থেকে প্রাপ্ত, যা বেশিরভাগ আলেমদের দ্বারা হারাম বলে বিবেচিত।",
      zh: "源自胭脂虫（胭脂红），大多数学者认为这是非清真的（Haram）。",
      fa: "به دست آمده از حشره کوچینیل (کارمین) که توسط بیشتر علما حرام دانسته می‌شود.",
      es: "Derivado del insecto cochinilla (Carmín), que es considerado Haram por la mayoría de los eruditos.",
      hi: "कोचीनियल कीट (कारमाइन) से प्राप्त, जिसे अधिकांश विद्वानों द्वारा हराम माना जाता है।",
      uz: "Aksariyat ulamolar tomonidan harom deb hisoblangan kochenil hasharotidan (Karmin) olingan.",
      kk: "Көптеген ғалымдар харам деп санайтын кошениль жәндігінен (Кармин) алынған.",
      ky: "Көптөгөн аалымдар арам деп эсептеген кошениль курт-кумурскасынан (Кармин) алынган.",
      so: "Waxaa laga soo qaatay cayayaanka cochineal (Carmine), kaas oo culimo badani u arkaan Xaaraan.",
      ha: "An samo shi daga kwarin cochineal (Carmine), wanda yawancin malamai ke ganin Haram ne.",
      sw: "Inatokana na mdudu wa cochineal (Carmine), ambayo inachukuliwa kuwa ni Haramu na wanazuoni wengi.",
      ps: "د کوچنیل حشرې (کارمین) څخه ترلاسه شوی، کوم چې د ډیری پوهانو لخوا حرام ګڼل کیږي.",
      tl: "Nagmula sa insekto ng cochineal (Carmine), na itinuturing na Haram ng karamihan sa mga iskolar.",
      ku: "Lêderketî ji mêşhingivê cochineal (Carmine), ku ji aliyê piraniya zanyaran ve wekî Heram tê dîtin.",
      ml: "മിക്ക പണ്ഡിതന്മാരും ഹറാം ആയി കണക്കാക്കുന്ന കൊച്ചിനിയൽ പ്രാണികളിൽ (കാർമൈൻ) നിന്ന് ഉരുത്തിരിഞ്ഞത്."
    }
  },
  {
    id: "E471",
    names: [
      "e471", "mono- and diglycerides", "أحادي وثنائي الجليسريدات", "e472",
      "mono- et diglycérides", "mono- dan digliserida", "mono- ve digliseridler",
      "mono- und diglyceride", "моно- и диглицериды", "مونو اور ڈائی گلیسرائڈز",
      "মনো- এবং ডিগ্লিসারাইডস", "单甘油酯和双甘油酯", "مونو و دی‌گلیسیرید", "mono- y diglicéridos",
      "मोनो- और डिग्लिसराइड्स", "mono- va diglitseridlar", "моно- және диглицеридтер",
      "моно- жана диглицериддер", "mono- iyo diglycerides", "mono- da diglycerides",
      "mono- na diglycerides", "مونو او ډای ګلیسریډز", "mono- at diglycerides",
      "mono- û dîglîserîd", "മോണോ- ആൻഡ് ഡൈഗ്ലിസറൈഡുകൾ"
    ],
    i18nNames: {
      en: ["mono- and diglycerides"],
      ar: ["أحادي وثنائي الجليسريدات"],
      fr: ["mono- et diglycérides"],
      id: ["mono- dan digliserida"],
      tr: ["mono- ve digliseridler"],
      de: ["mono- und diglyceride"],
      ru: ["моно- и диглицериды"],
      ur: ["مونو اور ڈائی گلیسرائڈز"],
      bn: ["মনো- এবং ডিগ্লিসারাইডস"],
      zh: ["单甘油酯和双甘油酯"],
      fa: ["مونو و دی‌گلیسیرید"],
      es: ["mono- y diglicéridos"],
      hi: ["मोनो- और डिग्लिसराइड्स"],
      uz: ["mono- va diglitseridlar"],
      kk: ["моно- және диглицеридтер"],
      ky: ["моно- жана диглицериддер"],
      so: ["mono- iyo diglycerides"],
      ha: ["mono- da diglycerides"],
      sw: ["mono- na diglycerides"],
      ps: ["مونو او ډای ګلیسریډز"],
      tl: ["mono- at diglycerides"],
      ku: ["mono- û dîglîserîd"],
      ml: ["മോണോ- ആൻഡ് ഡൈഗ്ലിസറൈഡുകൾ"]
    },
    status: HalalStatus.DOUBTFUL,
    reason: {
      ar: "غير محدد: قد يكون مستخرجاً من دهون حيوانية (خنزير أو بقر غير مذبوح حلال) أو من مصادر نباتية. يتطلب التحقق من المصدر.",
      en: "Unspecified: Can be derived from animal fats (pork or non-zabiha beef) or plant sources. Requires verification.",
      fr: "Non spécifié : Peut être dérivé de graisses animales (porc ou bœuf non-zabiha) ou de sources végétales. Nécessite une vérification.",
      id: "Tidak ditentukan: Dapat berasal dari lemak hewani (babi atau sapi non-zabiha) atau sumber nabati. Memerlukan verifikasi.",
      tr: "Şüpheli: Hayvansal yağlardan (domuz veya zabiha olmayan sığır) veya bitkisel kaynaklardan elde edilebilir. Doğrulama gerektirir.",
      de: "Nicht spezifiziert: Kann aus tierischen Fetten (Schwein oder nicht-Zabiha-Rind) oder pflanzlichen Quellen stammen. Erfordert Überprüfung.",
      ru: "Сомнительно: Может быть получено из животных жиров (свинина или говядина не-забиха) или растительных источников. Требует проверки.",
      ur: "مشکوک: جانوروں کی چربی (سور یا غیر ذبیحہ گائے) یا پودوں کے ذرائع سے حاصل کیا جا سکتا ہے۔ تصدیق کی ضرورت ہے۔",
      ms: "Tidak dinyatakan: Boleh berasal daripada lemak haiwan (babi atau lembu bukan zabiha) atau sumber tumbuhan. Memerlukan pengesahan.",
      bn: "সন্দেহজনক: পশুর চর্বি (শূকর বা অ-জাবিহা গরুর মাংস) বা উদ্ভিদের উত্স থেকে প্রাপ্ত হতে পারে। যাচাইকরণ প্রয়োজন।",
      zh: "未指明：可能源自动物脂肪（猪肉或非清真屠宰的牛肉）或植物来源。需要验证。",
      fa: "مشکوک: ممکن است از چربی‌های حیوانی (خوک یا گاو غیر ذبیحه) یا منابع گیاهی به دست آید. نیاز به بررسی دارد.",
      es: "No especificado: Puede derivar de grasas animales (cerdo o carne de res no zabiha) o fuentes vegetales. Requiere verificación.",
      hi: "संदिग्ध: पशु वसा (सूअर या गैर-ज़बीहा गोमांस) या पौधों के स्रोतों से प्राप्त किया जा सकता है। सत्यापन की आवश्यकता है।",
      uz: "Shubhali: Hayvon yog'lari (cho'chqa yoki zabiha bo'lmagan mol go'shti) yoki o'simlik manbalaridan olinishi mumkin. Tekshirishni talab qiladi.",
      kk: "Күмәнді: Жануарлар майларынан (шошқа немесе забиха емес сиыр еті) немесе өсімдік көздерінен алынуы мүмкін. Тексеруді қажет етеді.",
      ky: "Күмөндүү: Жаныбарлардын майларынан (чочко же забиха эмес уй эти) же өсүмдүк булактарынан алынышы мүмкүн. Текшерүүнү талап кылат.",
      so: "Shaki leh: Waxaa laga yaabaa in laga soo qaatay dufanka xoolaha (doofaar ama hilibka lo'da ee aan zabiha ahayn) ama ilo dhirta. Waxay u baahan xaqiijin.",
      ha: "Shakka: Ana iya samunsa daga kitsen dabbobi (alade ko naman sa wanda ba zabiha ba) ko tushen tsiro. Yana buƙatar tabbatarwa.",
      sw: "Inatiliwa shaka: Inaweza kutokana na mafuta ya wanyama (nguruwe au ng'ombe asiye zabiha) au vyanzo vya mimea. Inahitaji uthibitisho.",
      ps: "شکمن: کیدای شي د څارویو غوړ (خنزیر یا غیر ذبیحه غوښه) یا د نباتاتو سرچینو څخه ترلاسه شي. تایید ته اړتیا لري.",
      tl: "Kaduda-duda: Maaaring magmula sa taba ng hayop (baboy o hindi zabiha na baka) o mga mapagkukunan ng halaman. Nangangailangan ng pag-verify.",
      ku: "Gumanbar: Dibe ku ji rûnên heywanan (beraz an goştê ga yê ne-zebîhe) an çavkaniyên nebatan were wergirtin. Pêdivî bi pejirandinê heye.",
      ml: "സംശയാസ്പദമായത്: മൃഗങ്ങളുടെ കൊഴുപ്പിൽ നിന്നോ (പന്നിയിറച്ചി അല്ലെങ്കിൽ സബിഹ അല്ലാത്ത ഗോമാംസം) സസ്യ സ്രോതസ്സുകളിൽ നിന്നോ ഉരുത്തിരിഞ്ഞതാകാം. പരിശോധന ആവശ്യമാണ്."
    }
  },
  {
    id: "E441",
    names: [
      "e441", "gelatin", "gelatine", "جيلاتين",
      "gélatine", "jelatin", "gelatine", "желатин", "جیلیٹن", "জেলাটিন", "明胶", "ژلاتین",
      "gelatina", "जिलेटिन", "jelatîn", "ജെലാറ്റിൻ"
    ],
    i18nNames: {
      en: ["gelatin", "gelatine"],
      ar: ["جيلاتين"],
      fr: ["gélatine"],
      tr: ["jelatin"],
      id: ["gelatine"],
      ru: ["желатин"],
      ur: ["جیلیٹن"],
      bn: ["জেলাটিন"],
      zh: ["明胶"],
      fa: ["ژلاتین"],
      es: ["gelatina"],
      hi: ["जिलेटिन"],
      ku: ["jelatîn"],
      ml: ["ജെലാറ്റിൻ"]
    },
    status: HalalStatus.DOUBTFUL,
    reason: {
      ar: "غير محدد: الجيلاتين قد يكون من الخنزير (حرام) أو بقر غير مذبوح حلال، أو نباتي/سمكي (حلال).",
      en: "Unspecified: Gelatin can be from pork (Haram), non-zabiha beef, or plant/fish (Halal).",
      fr: "Non spécifié : La gélatine peut provenir de porc (Haram), de bœuf non-zabiha ou de plantes/poissons (Halal).",
      id: "Tidak ditentukan: Gelatin bisa dari babi (Haram), sapi non-zabiha, atau tanaman/ikan (Halal).",
      tr: "Şüpheli: Jelatin domuzdan (Haram), zabiha olmayan sığırdan veya bitki/balıktan (Helal) olabilir.",
      de: "Nicht spezifiziert: Gelatine kann vom Schwein (Haram), nicht-Zabiha-Rind oder Pflanze/Fisch (Halal) stammen.",
      ru: "Сомнительно: Желатин может быть из свинины (Харам), говядины не-забиха или растений/рыбы (Халяль).",
      ur: "مشکوک: جیلیٹن سور (حرام)، غیر ذبیحہ گائے، یا پودے/مچھلی (حلال) سے ہو سکتا ہے۔",
      ms: "Tidak dinyatakan: Gelatin boleh daripada babi (Haram), lembu bukan zabiha, atau tumbuhan/ikan (Halal).",
      bn: "সন্দেহজনক: জেলটিন শূকর (হারাম), অ-জাবিহা গরুর মাংস, বা উদ্ভিদ/মাছ (হালাল) থেকে হতে পারে।",
      zh: "未指明：明胶可能来自猪肉（Haram）、非清真屠宰的牛肉或植物/鱼类（Halal）。",
      fa: "مشکوک: ژلاتین می‌تواند از خوک (حرام)، گاو غیر ذبیحه، یا گیاه/ماهی (حلال) باشد.",
      es: "No especificado: La gelatina puede ser de cerdo (Haram), carne de res no zabiha o plantas/pescado (Halal).",
      hi: "संदिग्ध: जिलेटिन सूअर (हराम), गैर-ज़बीहा गोमांस, या पौधे/मछली (हलाल) से हो सकता है।",
      uz: "Shubhali: Jelatin cho'chqa (Harom), zabiha bo'lmagan mol go'shti yoki o'simlik/baliqdan (Halol) bo'lishi mumkin.",
      kk: "Күмәнді: Желатин шошқадан (Харам), забиха емес сиыр етінен немесе өсімдік/балықтан (Халал) болуы мүмкін.",
      ky: "Күмөндүү: Желатин чочкодон (Арам), забиха эмес уй этинен же өсүмдүк/балыктан (Адал) болушу мүмкүн.",
      so: "Shaki leh: Gelatin wuxuu ka imaan karaa doofaar (Xaaraan), hilibka lo'da ee aan zabiha ahayn, ama dhir/kalluun (Xalaal).",
      ha: "Shakka: Gelatin na iya zama daga alade (Haram), naman sa wanda ba zabiha ba, ko tsiro/kifi (Halal).",
      sw: "Inatiliwa shaka: Gelatin inaweza kutokana na nguruwe (Haramu), ng'ombe asiye zabiha, au mmea/samaki (Halali).",
      ps: "شکمن: جیلاتین کیدای شي د خنزیر (حرام)، غیر ذبیحه غوښې، یا نبات/کبانو (حلال) څخه وي.",
      tl: "Kaduda-duda: Ang gelatin ay maaaring mula sa baboy (Haram), hindi zabiha na baka, o halaman/isda (Halal).",
      ku: "Gumanbar: Jelatîn dikare ji beraz (Heram), goştê ga yê ne-zebîhe, an nebat / masî (Helal) be.",
      ml: "സംശയാസ്പദമായത്: ജെലാറ്റിൻ പന്നിയിറച്ചി (ഹറാം), സബിഹ അല്ലാത്ത ഗോമാംസം, അല്ലെങ്കിൽ സസ്യങ്ങൾ/മത്സ്യം (ഹലാൽ) എന്നിവയിൽ നിന്നാകാം."
    }
  },
  {
    id: "PORK",
    names: [
      "pork", "lard", "bacon", "ham", "خنزير", "دهن خنزير", "لحم خنزير", "naman alade", "nguruwe",
      "porc", "graisse de porc", "jambon", "babi", "lemak babi", "domuz", "domuz yağı", "pastırma",
      "schweinefleisch", "schmalz", "speck", "schinken", "свинина", "свиной жир", "бекон", "ветчина",
      "سور کا گوشت", "سور کی چربی", "শূকরের মাংস", "লার্ড", "猪肉", "猪油", "培根", "火腿",
      "خوک", "گوشت خوک", "چربی خوک", "cerdo", "manteca de cerdo", "tocino", "jamón",
      "सूअर का मांस", "cho'chqa go'shti", "cho'chqa yog'i", "шошқа еті", "шошқа майы",
      "чочко эти", "чочко майы", "hilib doofaar", "mafuta ya nguruwe", "د خنزیر غوښه", "د خنزیر غوړ",
      "taba ng baboy", "hamon", "beraz", "rûnê beraz", "പന്നിയിറച്ചി", "പന്നിക്കൊഴുപ്പ്"
    ],
    i18nNames: {
      en: ["pork", "lard", "bacon", "ham"],
      ar: ["خنزير", "دهن خنزير", "لحم خنزير"],
      ha: ["naman alade"],
      sw: ["nguruwe"],
      fr: ["porc", "graisse de porc", "jambon"],
      id: ["babi", "lemak babi"],
      tr: ["domuz", "domuz yağı", "pastırma"],
      de: ["schweinefleisch", "schmalz", "speck", "schinken"],
      ru: ["свинина", "свиной жир", "бекон", "ветчина"],
      ur: ["سور کا گوشت", "سور کی چربی"],
      bn: ["শূকরের মাংস", "লার্ড"],
      zh: ["猪肉", "猪油", "培根", "火腿"],
      fa: ["خوک", "گوشت خوک", "چربی خوک"],
      es: ["cerdo", "manteca de cerdo", "tocino", "jamón"],
      hi: ["सूअर का मांस"],
      uz: ["cho'chqa go'shti", "cho'chqa yog'i"],
      kk: ["шошқа еті", "шошқа майы"],
      ky: ["чочко эти", "чочко майы"],
      so: ["hilib doofaar", "mafuta ya nguruwe"],
      ps: ["د خنزیر غوښه", "د خنزیر غوړ"],
      tl: ["taba ng baboy", "hamon"],
      ku: ["beraz", "rûnê beraz"],
      ml: ["പന്നിയിറച്ചി", "പന്നിക്കൊഴുപ്പ്"]
    },
    status: HalalStatus.HARAM,
    reason: {
      ar: "يحتوي على الخنزير أو مشتقاته وهو محرم قطعاً.",
      en: "Contains pork or its derivatives, which is strictly Haram.",
      fr: "Contient du porc ou ses dérivés, ce qui est strictement Haram.",
      id: "Mengandung babi atau turunannya, yang secara tegas Haram.",
      tr: "Kesinlikle Haram olan domuz eti veya türevlerini içerir.",
      de: "Enthält Schweinefleisch oder dessen Derivate, was streng Haram ist.",
      ru: "Содержит свинину или ее производные, что строго Харам.",
      ur: "اس میں سور کا گوشت یا اس کے مشتقات شامل ہیں، جو سختی سے حرام ہے۔",
      ms: "Mengandungi babi atau derivatifnya, yang dilarang keras (Haram).",
      bn: "শূকরের মাংস বা এর ডেরিভেটিভ রয়েছে, যা কঠোরভাবে হারাম।",
      zh: "含有猪肉或其衍生物，这是严格禁止的（Haram）。",
      fa: "حاوی خوک یا مشتقات آن است که اکیداً حرام است.",
      es: "Contiene cerdo o sus derivados, lo cual es estrictamente Haram.",
      hi: "इसमें सूअर का मांस या उसके डेरिवेटिव शामिल हैं, जो सख्त हराम है।",
      uz: "Tarkibida cho'chqa go'shti yoki uning hosilalari mavjud bo'lib, ular qat'iyan haromdir.",
      kk: "Құрамында шошқа еті немесе оның туындылары бар, бұл қатаң Харам.",
      ky: "Курамында чочконун эти же анын туундулары бар, бул катуу Арам.",
      so: "Waxaa ku jira hilib doofaar ama waxyaabaha laga soo minguuriyay, taas oo si adag u Xaaraan ah.",
      ha: "Ya ƙunshi naman alade ko abubuwan da suka samo asali daga gare shi, wanda ke da tsananin Haram.",
      sw: "Ina nguruwe au bidhaa zake, ambayo ni Haramu kabisa.",
      ps: "د خنزیر غوښه یا د هغې مشتقات لري، کوم چې په کلکه حرام دي.",
      tl: "Naglalaman ng baboy o mga derivatives nito, na mahigpit na Haram.",
      ku: "Beraz an jêderên wê dihewîne, ku bi tundî Heram e.",
      ml: "പന്നിയിറച്ചിയോ അതിൻ്റെ ഡെറിവേറ്റീവുകളോ അടങ്ങിയിരിക്കുന്നു, ഇത് കർശനമായി ഹറാം ആണ്."
    }
  },
  {
    id: "ALCOHOL",
    names: [
      "alcohol", "ethanol", "wine", "beer", "rum", "liquor", "كحول", "إيثانول", "نبيذ", "بيرة", "خمر", "giya", "pombe",
      "alcool", "éthanol", "vin", "bière", "rhum", "liqueur", "etanol", "anggur", "bir", "alkol", "şarap", "likör",
      "wein", "bier", "алкоголь", "этанол", "вино", "пиво", "ликер", "الکحل", "شراب", "بیئر",
      "অ্যালকোহল", "ইথানল", "ওয়াইন", "বিয়ার", "酒精", "乙醇", "葡萄酒", "啤酒", "朗姆酒",
      "الکل", "اتانول", "آبجو", "vino", "cerveza", "ron", "licor", "शराब", "इथेनॉल", "वाइन", "बीयर",
      "spirt", "pivo", "шарап", "сыра", "aalkolo", "khamri", "barasa", "mvinyo", "serbesa",
      "alak", "şerab", "bîra", "മദ്യം", "എത്തനോൾ", "വൈൻ", "ബിയർ"
    ],
    i18nNames: {
      en: ["alcohol", "ethanol", "wine", "beer", "rum", "liquor"],
      ar: ["كحول", "إيثانول", "نبيذ", "بيرة", "خمر"],
      ha: ["giya", "barasa"],
      sw: ["pombe", "mvinyo"],
      fr: ["alcool", "éthanol", "vin", "bière", "rhum", "liqueur"],
      id: ["etanol", "anggur", "bir"],
      tr: ["alkol", "şarap", "likör"],
      de: ["wein", "bier"],
      ru: ["алкоголь", "этанол", "вино", "пиво", "ликер"],
      ur: ["الکحل", "شراب", "بیئر"],
      bn: ["অ্যালকোহল", "ইথানল", "ওয়াইন", "বিয়ার"],
      zh: ["酒精", "乙醇", "葡萄酒", "啤酒", "朗姆酒"],
      fa: ["الکل", "اتانول", "آبجو"],
      es: ["vino", "cerveza", "ron", "licor"],
      hi: ["शराब", "इथेनॉल", "वाइन", "बीयर"],
      uz: ["spirt", "pivo"],
      kk: ["шарап", "сыра"],
      so: ["aalkolo", "khamri"],
      tl: ["serbesa", "alak"],
      ku: ["şerab", "bîra"],
      ml: ["മദ്യം", "എത്തനോൾ", "വൈൻ", "ബിയർ"]
    },
    status: HalalStatus.HARAM,
    reason: {
      ar: "يحتوي على كحول أو مسكرات.",
      en: "Contains alcohol or intoxicants.",
      fr: "Contient de l'alcool ou des substances enivrantes.",
      id: "Mengandung alkohol atau minuman keras.",
      tr: "Alkol veya sarhoş edici maddeler içerir.",
      de: "Enthält Alkohol oder Rauschmittel.",
      ru: "Содержит алкоголь или опьяняющие вещества.",
      ur: "اس میں الکحل یا نشہ آور اشیاء شامل ہیں۔",
      ms: "Mengandungi alkohol atau bahan yang memabukkan.",
      bn: "অ্যালকোহল বা নেশাজাতীয় দ্রব্য রয়েছে।",
      zh: "含有酒精或麻醉品。",
      fa: "حاوی الکل یا مواد مست کننده است.",
      es: "Contiene alcohol o intoxicantes.",
      hi: "शराब या नशीले पदार्थ शामिल हैं।",
      uz: "Tarkibida spirtli ichimliklar yoki mast qiluvchi moddalar mavjud.",
      kk: "Құрамында алкоголь немесе мас қылатын заттар бар.",
      ky: "Курамында спирт же мас кылуучу заттар бар.",
      so: "Waxaa ku jira aalkolo ama waxyaabaha maanka dooriya.",
      ha: "Ya ƙunshi barasa ko abubuwan maye.",
      sw: "Ina pombe au vileo.",
      ps: "الکول یا نشه یي توکي لري.",
      tl: "Naglalaman ng alkohol o mga nakalalasing.",
      ku: "Alkol an serxweşker dihewîne.",
      ml: "മദ്യമോ ലഹരിവസ്തുക്കളോ അടങ്ങിയിരിക്കുന്നു."
    }
  },
  {
    id: "E904",
    names: [
      "e904", "shellac", "الشيلاك", "شيلاك",
      "gomme laque", "syelak", "şellak", "schellack", "шеллак", "شلاک", "শেলাক", "紫胶", "虫胶",
      "goma laca", "चपड़ा", "शेलैक", "shellak", "şelak", "ഷെല്ലക്"
    ],
    i18nNames: {
      en: ["shellac"],
      ar: ["الشيلاك", "شيلاك"],
      fr: ["gomme laque"],
      id: ["syelak"],
      tr: ["şellak"],
      de: ["schellack"],
      ru: ["шеллак"],
      ur: ["شلاک"],
      bn: ["শেলাক"],
      zh: ["紫胶", "虫胶"],
      es: ["goma laca"],
      hi: ["चपड़ा", "शेलैक"],
      uz: ["shellak"],
      ku: ["şelak"],
      ml: ["ഷെല്ലക്"]
    },
    status: HalalStatus.DOUBTFUL,
    reason: {
      ar: "غير محدد: إفرازات حشرية، يختلف العلماء في حكمها.",
      en: "Unspecified: Insect secretions, scholars differ on its ruling.",
      fr: "Non spécifié : Sécrétions d'insectes, les savants divergent sur son jugement.",
      id: "Tidak ditentukan: Sekresi serangga, para ulama berbeda pendapat tentang hukumnya.",
      tr: "Şüpheli: Böcek salgıları, alimler hükmü konusunda ihtilaf etmiştir.",
      de: "Nicht spezifiziert: Insektenausscheidungen, Gelehrte sind sich über das Urteil uneinig.",
      ru: "Сомнительно: Выделения насекомых, ученые расходятся во мнениях относительно этого.",
      ur: "مشکوک: کیڑوں کی رطوبتیں، علماء اس کے حکم پر اختلاف کرتے ہیں۔",
      ms: "Tidak dinyatakan: Rembesan serangga, ulama berbeza pendapat tentang hukumnya.",
      bn: "সন্দেহজনক: পোকামাকড়ের নিঃসরণ, আলেমগণ এর হুকুম সম্পর্কে ভিন্নমত পোষণ করেন।",
      zh: "未指明：昆虫分泌物，学者对其裁决存在分歧。",
      fa: "مشکوک: ترشحات حشرات، علما در حکم آن اختلاف دارند.",
      es: "No especificado: Secreciones de insectos, los eruditos difieren sobre su fallo.",
      hi: "संदिग्ध: कीट स्राव, विद्वान इसके फैसले पर भिन्न हैं।",
      uz: "Shubhali: Hasharotlar ajratmalari, ulamolar uning hukmi borasida ixtilof qilishadi.",
      kk: "Күмәнді: Жәндіктердің секрециялары, ғалымдар оның үкіміне қатысты әртүрлі пікірде.",
      ky: "Күмөндүү: Курт-кумурскалардын бөлүп чыгаруулары, аалымдар анын өкүмү боюнча ар кандай пикирде.",
      so: "Shaki leh: Dheecaannada cayayaanka, culimadu way isku khilaafsan yihiin xukunkeeda.",
      ha: "Shakka: Ruwan kwari, malamai sun yi sabani kan hukuncinsa.",
      sw: "Inatiliwa shaka: Utoaji wa wadudu, wanazuoni wanatofautiana juu ya hukumu yake.",
      ps: "شکمن: د حشراتو رطوبت، پوهان د هغې په حکم کې اختلاف لري.",
      tl: "Kaduda-duda: Mga pagtatago ng insekto, nagkakaiba ang mga iskolar sa pasya nito.",
      ku: "Gumanbar: Derdanên kêzikan, zanyar li ser biryara wê ji hev cûda dibin.",
      ml: "സംശയാസ്പദമായത്: പ്രാണികളുടെ സ്രവങ്ങൾ, പണ്ഡിതന്മാർ അതിൻ്റെ വിധിയിൽ വ്യത്യാസപ്പെട്ടിരിക്കുന്നു."
    }
  },
  {
    id: "E542",
    names: [
      "e542", "bone phosphate", "فوسفات العظام",
      "phosphate d'os", "fosfat tulang", "kemik fosfatı", "knochenphosphat", "костный фосфат",
      "ہڈیوں کا فاسفیٹ", "হাড়ের ফসফেট", "骨磷酸盐", "فسفات استخوان", "fosfato de hueso",
      "अस्थि फॉस्फेट", "suyak fosfati", "сүйек фосфаты", "сөөк фосфаты", "fosfate lafaha",
      "phosphate na ƙashi", "fosfeti ya mifupa", "د هډوکو فاسفیټ", "fosfata hestî", "അസ്ഥി ഫോസ്ഫേറ്റ്"
    ],
    i18nNames: {
      en: ["bone phosphate"],
      ar: ["فوسفات العظام"],
      fr: ["phosphate d'os"],
      id: ["fosfat tulang"],
      tr: ["kemik fosfatı"],
      de: ["knochenphosphat"],
      ru: ["костный фосфат"],
      ur: ["ہڈیوں کا فاسفیٹ"],
      bn: ["হাড়ের ফসফেট"],
      zh: ["骨磷酸盐"],
      fa: ["فسفات استخوان"],
      es: ["fosfato de hueso"],
      hi: ["अस्थि फॉस्फेट"],
      uz: ["suyak fosfati"],
      kk: ["сүйек фосфаты"],
      ky: ["сөөк фосфаты"],
      so: ["fosfate lafaha"],
      ha: ["phosphate na ƙashi"],
      sw: ["fosfeti ya mifupa"],
      ps: ["د هډوکو فاسفیټ"],
      ku: ["fosfata hestî"],
      ml: ["അസ്ഥി ഫോസ്ഫേറ്റ്"]
    },
    status: HalalStatus.DOUBTFUL,
    reason: {
      ar: "غير محدد: مستخرج من عظام الحيوانات، قد تكون غير مذبوحة حلال أو خنزير.",
      en: "Unspecified: Derived from animal bones, which may be non-zabiha or pork.",
      fr: "Non spécifié : Dérivé d'os d'animaux, qui peuvent être non-zabiha ou de porc.",
      id: "Tidak ditentukan: Berasal dari tulang hewan, yang mungkin non-zabiha atau babi.",
      tr: "Şüpheli: Zabiha olmayan veya domuz olabilen hayvan kemiklerinden elde edilir.",
      de: "Nicht spezifiziert: Gewonnen aus Tierknochen, die nicht-Zabiha oder vom Schwein sein können.",
      ru: "Сомнительно: Получено из костей животных, которые могут быть не-забиха или свининой.",
      ur: "مشکوک: جانوروں کی ہڈیوں سے ماخوذ، جو غیر ذبیحہ یا سور ہو سکتی ہیں۔",
      ms: "Tidak dinyatakan: Berasal daripada tulang haiwan, yang mungkin bukan zabiha atau babi.",
      bn: "সন্দেহজনক: পশুর হাড় থেকে প্রাপ্ত, যা অ-জাবিহা বা শূকর হতে পারে।",
      zh: "未指明：源自动物骨骼，可能是非清真屠宰的动物或猪肉。",
      fa: "مشکوک: به دست آمده از استخوان حیوانات، که ممکن است غیر ذبیحه یا خوک باشد.",
      es: "No especificado: Derivado de huesos de animales, que pueden ser no zabiha o cerdo.",
      hi: "संदिग्ध: जानवरों की हड्डियों से प्राप्त, जो गैर-ज़बीहा या सूअर हो सकता है।",
      uz: "Shubhali: Hayvon suyaklaridan olingan bo'lib, ular zabiha bo'lmagan yoki cho'chqa bo'lishi mumkin.",
      kk: "Күмәнді: Жануарлар сүйектерінен алынған, олар забиха емес немесе шошқа болуы мүмкін.",
      ky: "Күмөндүү: Жаныбарлардын сөөктөрүнөн алынган, алар забиха эмес же чочко болушу мүмкүн.",
      so: "Shaki leh: Waxaa laga soo qaatay lafaha xoolaha, kuwaas oo laga yaabo inay yihiin kuwa aan zabiha ahayn ama doofaar.",
      ha: "Shakka: An samo shi daga ƙasusuwan dabbobi, waɗanda ƙila ba zabiha ba ne ko alade.",
      sw: "Inatiliwa shaka: Inatokana na mifupa ya wanyama, ambayo inaweza kuwa si zabiha au nguruwe.",
      ps: "شکمن: د څارویو له هډوکو څخه ترلاسه شوي، کوم چې ممکن غیر ذبیحه یا خنزیر وي.",
      tl: "Kaduda-duda: Nagmula sa mga buto ng hayop, na maaaring hindi zabiha o baboy.",
      ku: "Gumanbar: Ji hestiyên heywanan tê wergirtin, ku dibe ku ne-zebîhe an beraz be.",
      ml: "സംശയാസ്പദമായത്: മൃഗങ്ങളുടെ അസ്ഥികളിൽ നിന്ന് ഉരുത്തിരിഞ്ഞത്, ഇത് സബിഹ അല്ലാത്തതോ പന്നിയിറച്ചിയോ ആകാം."
    }
  },
  {
    id: "E920",
    names: [
      "e920", "l-cysteine", "سيستين", "e921",
      "l-cystéine", "l-sistein", "l-cystein", "l-цистеин", "ایل سسٹین", "এল-সিস্টাইন",
      "l-半胱氨酸", "ال-سیستئین", "l-cisteína", "एल-सिस्टीन", "l-tsistein", "l-цистеин",
      "ایل سیسټین", "l-sîsteîn", "എൽ-സിസ്റ്റീൻ"
    ],
    i18nNames: {
      en: ["l-cysteine"],
      ar: ["سيستين"],
      fr: ["l-cystéine"],
      id: ["l-sistein"],
      de: ["l-cystein"],
      ru: ["l-цистеин"],
      ur: ["ایل سسٹین"],
      bn: ["এল-সিস্টাইন"],
      zh: ["l-半胱氨酸"],
      fa: ["ال-سیستئین"],
      es: ["l-cisteína"],
      hi: ["एल-सिस्टीन"],
      uz: ["l-tsistein"],
      kk: ["l-цистеин"],
      ps: ["ایل سیسټین"],
      ku: ["l-sîsteîn"],
      ml: ["എൽ-സിസ്റ്റീൻ"]
    },
    status: HalalStatus.DOUBTFUL,
    reason: {
      ar: "غير محدد: قد يستخرج من شعر الإنسان أو ريش البط أو شعر الخنزير، وقد يكون صناعياً.",
      en: "Unspecified: Can be derived from human hair, duck feathers, pig hair, or synthetically.",
      fr: "Non spécifié : Peut être dérivé de cheveux humains, de plumes de canard, de poils de porc ou de manière synthétique.",
      id: "Tidak ditentukan: Dapat berasal dari rambut manusia, bulu bebek, bulu babi, atau secara sintetis.",
      tr: "Şüpheli: İnsan saçından, ördek tüyünden, domuz kılından veya sentetik olarak elde edilebilir.",
      de: "Nicht spezifiziert: Kann aus menschlichem Haar, Entenfedern, Schweineborsten oder synthetisch gewonnen werden.",
      ru: "Сомнительно: Может быть получено из человеческих волос, утиных перьев, свиной щетины или синтетически.",
      ur: "مشکوک: انسانی بالوں، بطخ کے پروں، سور کے بالوں، یا مصنوعی طور پر حاصل کیا جا سکتا ہے۔",
      ms: "Tidak dinyatakan: Boleh berasal daripada rambut manusia, bulu itik, bulu babi, atau secara sintetik.",
      bn: "সন্দেহজনক: মানুষের চুল, হাঁসের পালক, শূকরের চুল বা কৃত্রিমভাবে প্রাপ্ত হতে পারে।",
      zh: "未指明：可能源自人发、鸭毛、猪毛或合成产生。",
      fa: "مشکوک: ممکن است از موی انسان، پر اردک، موی خوک یا به صورت مصنوعی به دست آید.",
      es: "No especificado: Puede derivar de cabello humano, plumas de pato, pelo de cerdo o sintéticamente.",
      hi: "संदिग्ध: मानव बाल, बत्तख के पंख, सूअर के बाल, या कृत्रिम रूप से प्राप्त किया जा सकता है।",
      uz: "Shubhali: Inson sochlari, o'rdak patlari, cho'chqa sochlari yoki sintetik tarzda olinishi mumkin.",
      kk: "Күмәнді: Адам шашынан, үйрек қауырсынынан, шошқа қылынан немесе синтетикалық түрде алынуы мүмкін.",
      ky: "Күмөндүү: Адамдын чачынан, өрдөктүн жүнүнөн, чочконун жүнүнөн же синтетикалык жол менен алынышы мүмкүн.",
      so: "Shaki leh: Waxaa laga yaabaa in laga soo qaatay timaha bini'aadamka, baalasha shinbiraha, timaha doofaarka, ama si macmal ah.",
      ha: "Shakka: Ana iya samunsa daga gashin mutum, fuka-fukan agwagwa, gashin alade, ko ta hanyar sinadarai.",
      sw: "Inatiliwa shaka: Inaweza kutokana na nywele za binadamu, manyoya ya bata, nywele za nguruwe, au kwa njia ya kisintetiki.",
      ps: "شکمن: کیدای شي د انسان ویښتو، د مرغۍ بڼکو، د خنزیر ویښتو، یا په مصنوعي توګه ترلاسه شي.",
      tl: "Kaduda-duda: Maaaring magmula sa buhok ng tao, balahibo ng pato, buhok ng baboy, o synthetically.",
      ku: "Gumanbar: Dibe ku ji porê mirovan, perrên ordek, mûyê beraz, an bi awayekî sentetîk were wergirtin.",
      ml: "സംശയാസ്പദമായത്: മനുഷ്യൻ്റെ മുടി, താറാവിൻ്റെ തൂവലുകൾ, പന്നിയുടെ മുടി അല്ലെങ്കിൽ കൃത്രിമമായി ഉരുത്തിരിഞ്ഞതാകാം."
    }
  },
  {
    id: "RENNET",
    names: [
      "rennet", "pepsin", "منفحة", "بيبسين", "أنزيم الرينيت",
      "présure", "pepsine", "peynir mayası", "lab", "сычужный фермент", "реннет",
      "رینٹ", "پیپسن", "রেনেট", "পেপসিন", "凝乳酶", "胃蛋白酶", "مایه پنیر", "پپسین",
      "cuajo", "pepsina", "रेनेट", "пепсин", "pepsîn", "റെന്നറ്റ്", "പെപ്സിൻ"
    ],
    i18nNames: {
      en: ["rennet", "pepsin"],
      ar: ["منفحة", "بيبسين", "أنزيم الرينيت"],
      fr: ["présure", "pepsine"],
      tr: ["peynir mayası"],
      de: ["lab"],
      ru: ["сычужный фермент"],
      uz: ["rennet"],
      ur: ["رینٹ", "پیپسن"],
      bn: ["রেনেট", "পেপসিন"],
      zh: ["凝乳酶", "胃蛋白酶"],
      fa: ["مایه پنیر", "پپسین"],
      es: ["cuajo", "pepsina"],
      hi: ["रेनेट", "пепсин"],
      ku: ["pepsîn"],
      ml: ["റെന്നറ്റ്", "പെപ്സിൻ"]
    },
    status: HalalStatus.DOUBTFUL,
    reason: {
      ar: "غير محدد: إنزيمات تستخرج غالباً من معدة العجول أو الخنازير. حلال إذا كانت ميكروبية أو نباتية.",
      en: "Unspecified: Enzymes often derived from calf or pig stomachs. Halal if microbial or plant-based.",
      fr: "Non spécifié : Enzymes souvent dérivées d'estomacs de veau ou de porc. Halal si d'origine microbienne ou végétale.",
      id: "Tidak ditentukan: Enzim yang sering berasal dari lambung anak sapi atau babi. Halal jika berbasis mikroba atau tanaman.",
      tr: "Şüpheli: Genellikle buzağı veya domuz midelerinden elde edilen enzimler. Mikrobiyal veya bitkisel bazlı ise Helaldir.",
      de: "Nicht spezifiziert: Enzyme, die oft aus Kälber- oder Schweinemägen gewonnen werden. Halal, wenn mikrobiell oder pflanzlich.",
      ru: "Сомнительно: Ферменты часто получают из желудков телят или свиней. Халяль, если микробного или растительного происхождения.",
      ur: "مشکوک: انزائمز اکثر بچھڑے یا سور کے معدے سے حاصل کیے جاتے ہیں۔ حلال اگر مائکروبیل یا پودوں پر مبنی ہو۔",
      ms: "Tidak dinyatakan: Enzim yang sering berasal daripada perut anak lembu atau babi. Halal jika berasaskan mikrob atau tumbuhan.",
      bn: "সন্দেহজনক: এনজাইমগুলি প্রায়শই বাছুর বা শূকরের পেট থেকে প্রাপ্ত হয়। মাইক্রোবিয়াল বা উদ্ভিদ-ভিত্তিক হলে হালাল।",
      zh: "未指明：通常提取自小牛或猪胃的酶。如果是微生物或植物来源的，则为清真（Halal）。",
      fa: "مشکوک: آنزیم‌هایی که اغلب از معده گوساله یا خوک به دست می‌آیند. اگر میکروبی یا گیاهی باشد حلال است.",
      es: "No especificado: Enzimas a menudo derivadas de estómagos de ternera o cerdo. Halal si es de origen microbiano o vegetal.",
      hi: "संदिग्ध: एंजाइम अक्सर बछड़े या सूअर के पेट से प्राप्त होते हैं। माइक्रोबियल या पौधे-आधारित होने पर हलाल।",
      uz: "Shubhali: Fermentlar ko'pincha buzoq yoki cho'chqa oshqozonidan olinadi. Agar mikrobial yoki o'simlikka asoslangan bo'lsa, halol.",
      kk: "Күмәнді: Ферменттер көбінесе бұзау немесе шошқа асқазанынан алынады. Микробтық немесе өсімдік негізіндегі болса Халал.",
      ky: "Күмөндүү: Ферменттер көбүнчө музоо же чочконун ашказанынан алынат. Микробдук же өсүмдүк негизиндеги болсо Адал.",
      so: "Shaki leh: Enzymes inta badan laga soo qaatay caloosha weylaha ama doofaarka. Xalaal haddii ay tahay mikrobial ama dhir.",
      ha: "Shakka: Enzymes sau da yawa ana samun su daga cikin maruƙa ko alade. Halal idan na microbial ne ko na tsiro.",
      sw: "Inatiliwa shaka: Vimeng'enya mara nyingi hutokana na matumbo ya ndama au nguruwe. Halali ikiwa inatokana na vijidudu au mimea.",
      ps: "شکمن: انزایمونه ډیری وختونه د خوسکي یا خنزیر له معدې څخه ترلاسه کیږي. حلال که میکروبیل یا نبات پر بنسټ وي.",
      tl: "Kaduda-duda: Mga enzyme na madalas nagmula sa tiyan ng guya o baboy. Halal kung microbial o plant-based.",
      ku: "Gumanbar: Enzîmên ku bi gelemperî ji zikê golik an berazan têne wergirtin. Helal e heke mîkrobî an li ser bingeha nebatan be.",
      ml: "സംശയാസ്പദമായത്: എൻസൈമുകൾ പലപ്പോഴും പശുക്കിടാവിൻ്റെയോ പന്നിയുടെയോ ആമാശയത്തിൽ നിന്ന് ഉരുത്തിരിഞ്ഞതാണ്. സൂക്ഷ്മജീവികളോ സസ്യങ്ങളെ അടിസ്ഥാനമാക്കിയുള്ളതോ ആണെങ്കിൽ ഹലാൽ."
    }
  },
  {
    id: "E100",
    names: [
      "e100", "curcumin", "كركمين",
      "curcumine", "kurkumin", "куркумин", "کرکومین", "কারকিউমিন", "姜黄素", "کورکومین",
      "curcumina", "करक्यूमिन", "kurkumîn", "കുർക്കുമിൻ"
    ],
    i18nNames: {
      en: ["curcumin"],
      ar: ["كركمين"],
      fr: ["curcumine"],
      id: ["kurkumin"],
      ru: ["куркумин"],
      ur: ["کرکومین"],
      bn: ["কারকিউমিন"],
      zh: ["姜黄素"],
      fa: ["کورکومین"],
      es: ["curcumina"],
      hi: ["करक्यूमिन"],
      ku: ["kurkumîn"],
      ml: ["കുർക്കുമിൻ"]
    },
    status: HalalStatus.HALAL,
    reason: {
      ar: "مسموح: مستخرج نباتي من الكركم.",
      en: "Permissible: Plant-based extract from turmeric.",
      fr: "Permissible : Extrait végétal de curcuma.",
      id: "Permissible: Ekstrak nabati dari kunyit.",
      tr: "Helal: Zerdeçaldan elde edilen bitkisel öz.",
      de: "Permissible: Pflanzlicher Extrakt aus Kurkuma.",
      ru: "Халяль: Растительный экстракт из куркумы.",
      ur: "مسموح: ہلدی سے پودوں پر مبنی عرق۔",
      ms: "Permissible: Ekstrak berasaskan tumbuhan daripada kunyit.",
      bn: "হালাল: হলুদ থেকে উদ্ভিদ-ভিত্তিক নির্যাস।",
      zh: "清真：姜黄的植物提取物。",
      fa: "مسموح: عصاره گیاهی از زردچوبه.",
      es: "Permissible: Extracto de origen vegetal de la cúrcuma.",
      hi: "हलाल: हल्दी से पौधे-आधारित अर्क।",
      uz: "Halol: Zerdechaldan o'simlikka asoslangan ekstrakt.",
      kk: "Халал: Куркумадан алынған өсімдік сығындысы.",
      ky: "Адал: Куркумадан алынган өсүмдүк экстракты.",
      so: "Xalaal: Soosaar dhirta ku salaysan oo laga helo turmeric.",
      ha: "Permissible: Cire tushen tsiro daga turmeric.",
      sw: "Halali: Dondoo inayotokana na mimea kutoka kwa manjano.",
      ps: "مسموح: د हल्दी څخه د نباتاتو پر بنسټ استخراج.",
      tl: "Permissible: Plant-based extract mula sa turmeric.",
      ku: "Helal: Ekstrakta nebatî ji zerdeçalê.",
      ml: "ഹലാൽ: മഞ്ഞളിൽ നിന്നുള്ള സസ്യ അധിഷ്ഠിത സത്തിൽ."
    }
  },
  {
    id: "E160a",
    names: [
      "e160a", "carotene", "كاروتين",
      "carotène", "karoten", "carotin", "каротин", "کیروٹین", "ক্যারোটিন", "胡萝卜素",
      "کاروتن", "caroteno", "कैरोटीन", "karotin", "کیروټین", "കരോട്ടിൻ"
    ],
    i18nNames: {
      en: ["carotene"],
      ar: ["كاروتين"],
      fr: ["carotène"],
      id: ["karoten"],
      de: ["carotin"],
      ru: ["каротин"],
      ur: ["کیروٹین"],
      bn: ["ক্যারোটিন"],
      zh: ["胡萝卜素"],
      fa: ["کاروتن"],
      es: ["caroteno"],
      hi: ["कैरोटीन"],
      uz: ["karotin"],
      ps: ["کیروټین"],
      ml: ["കരോട്ടിൻ"]
    },
    status: HalalStatus.HALAL,
    reason: {
      ar: "مسموح: مستخرج نباتي أو مصنع كيميائياً.",
      en: "Permissible: Plant-based or synthetically produced.",
      fr: "Permissible : D'origine végétale ou produit synthétiquement.",
      id: "Permissible: Berbasis tanaman atau diproduksi secara sintetis.",
      tr: "Helal: Bitkisel bazlı veya sentetik olarak üretilmiş.",
      de: "Permissible: Pflanzlich oder synthetisch hergestellt.",
      ru: "Халяль: Растительного происхождения или синтетически произведено.",
      ur: "مسموح: پودوں پر مبنی یا مصنوعی طور پر تیار کیا گیا ہے۔",
      ms: "Permissible: Berasaskan tumbuhan atau dihasilkan secara sintetik.",
      bn: "হালাল: উদ্ভিদ-ভিত্তিক বা কৃত্রিমভাবে উত্পাদিত।",
      zh: "清真：植物来源或合成生产的。",
      fa: "مسموح: گیاهی یا به صورت مصنوعی تولید شده است.",
      es: "Permissible: De origen vegetal o producido sintéticamente.",
      hi: "हलाल: पौधे-आधारित या कृत्रिम रूप से उत्पादित।",
      uz: "Halol: O'simlikka asoslangan yoki sintetik tarzda ishlab chiqarilgan.",
      kk: "Халал: Өсімдік негізіндегі немесе синтетикалық түрде өндірілген.",
      ky: "Адал: Өсүмдүк негизиндеги же синтетикалык жол менен өндүрүлгөн.",
      so: "Xalaal: Dhirta ku salaysan ama si macmal ah loo soo saaray.",
      ha: "Permissible: Tushen tsiro ko kuma wanda aka samar ta hanyar sinadarai.",
      sw: "Halali: Inayotokana na mimea au inayozalishwa kwa njia ya kisintetiki.",
      ps: "مسموح: د نباتاتو پر بنسټ یا په مصنوعي توګه تولید شوي.",
      tl: "Permissible: Plant-based o synthetically produced.",
      ku: "Helal: Li ser bingeha nebatan an bi awayekî sentetîk tê hilberandin.",
      ml: "ഹലാൽ: സസ്യങ്ങളെ അടിസ്ഥാനമാക്കിയുള്ളതോ കൃത്രിമമായി ഉത്പാദിപ്പിക്കുന്നതോ ആണ്."
    }
  },
  {
    id: "E322",
    names: [
      "e322", "lecithin", "ليسيثين",
      "lécithine", "lesitin", "лецитин", "لیسیتھین", "লেসিথিন", "卵磷脂", "لسیتین",
      "lecitina", "लेसिथिन", "letsitin", "لیسیتین", "lesîtîn", "ലെസിത്തിൻ"
    ],
    i18nNames: {
      en: ["lecithin"],
      ar: ["ليسيثين"],
      fr: ["lécithine"],
      id: ["lesitin"],
      ru: ["лецитин"],
      ur: ["لیسیتھین"],
      bn: ["লেসিথিন"],
      zh: ["卵磷脂"],
      fa: ["لسیتین"],
      es: ["lecitina"],
      hi: ["लेसिथिन"],
      uz: ["letsitin"],
      ps: ["لیسیتین"],
      ku: ["lesîtîn"],
      ml: ["ലെസിത്തിൻ"]
    },
    status: HalalStatus.DOUBTFUL,
    reason: {
      ar: "غير محدد: غالباً يستخرج من الصويا (حلال)، ولكن قد يستخرج من صفار البيض أو دهون حيوانية.",
      en: "Unspecified: Usually from soy (Halal), but can be from egg yolk or animal fats.",
      fr: "Non spécifié : Généralement issu du soja (Halal), mais peut provenir de jaune d'œuf ou de graisses animales.",
      id: "Tidak ditentukan: Biasanya dari kedelai (Halal), tetapi bisa dari kuning telur atau lemak hewani.",
      tr: "Şüpheli: Genellikle soyadan (Helal), ancak yumurta sarısı veya hayvansal yağlardan da olabilir.",
      de: "Nicht spezifiziert: Meistens aus Soja (Halal), kann aber auch aus Eigelb oder tierischen Fetten stammen.",
      ru: "Сомнительно: Обычно из сои (Халяль), но может быть из яичного желтка или животных жиров.",
      ur: "مشکوک: عام طور پر سویا (حلال) سے، لیکن انڈے کی زردی یا جانوروں کی چربی سے ہو سکتا ہے۔",
      ms: "Tidak dinyatakan: Biasanya daripada soya (Halal), tetapi boleh daripada kuning telur atau lemak haiwan.",
      bn: "সন্দেহজনক: সাধারণত সয়া (হালাল) থেকে, তবে ডিমের কুসুম বা পশুর চর্বি থেকে হতে পারে।",
      zh: "未指明：通常来自大豆（Halal），但也可能来自蛋黄或动物脂肪。",
      fa: "مشکوک: معمولاً از سویا (حلال) است، اما می‌تواند از زرده تخم مرغ یا چربی‌های حیوانی باشد.",
      es: "No especificado: Generalmente de soja (Halal), pero puede ser de yema de huevo o grasas animales.",
      hi: "संदिग्ध: आमतौर पर सोया (हलाल) से, लेकिन अंडे की जर्दी या पशु वसा से हो सकता है।",
      uz: "Shubhali: Odatda soyadan (Halol), lekin tuxum sarig'i yoki hayvon yog'laridan bo'lishi mumkin.",
      kk: "Күмәнді: Әдетте соядан (Халал), бірақ жұмыртқаның сарысынан немесе жануарлар майларынан болуы мүмкін.",
      ky: "Күмөндүү: Адатта соядан (Адал), бирок жумуртканын сарысынан же жаныбарлардын майларынан болушу мүмкүн.",
      so: "Shaki leh: Caadi ahaan soya (Xalaal), laakiin waxay ka imaan kartaa beedka jaallaha ah ama dufanka xoolaha.",
      ha: "Shakka: Yawanci daga waken soya (Halal), amma yana iya zama daga gwaiduwar kwai ko kitsen dabbobi.",
      sw: "Inatiliwa shaka: Kawaida kutoka kwa soya (Halali), lakini inaweza kuwa kutoka kwa kiini cha yai au mafuta ya wanyama.",
      ps: "شکمن: معمولا د سویا (حلال) څخه، مګر کیدای شي د هګۍ ژیړ یا د څارویو غوړ څخه وي.",
      tl: "Kaduda-duda: Karaniwang mula sa toyo (Halal), ngunit maaaring mula sa pula ng itlog o taba ng hayop.",
      ku: "Gumanbar: Bi gelemperî ji soya (Helal), lê dibe ku ji zerika hêkê an rûnên heywanan be.",
      ml: "സംശയാസ്പദമായത്: സാധാരണയായി സോയയിൽ നിന്ന് (ഹലാൽ), എന്നാൽ മുട്ടയുടെ മഞ്ഞക്കരു അല്ലെങ്കിൽ മൃഗങ്ങളുടെ കൊഴുപ്പിൽ നിന്നാകാം."
    }
  },
  {
    id: "E422",
    names: [
      "e422", "glycerol", "glycerin", "جليسرول", "جليسرين",
      "glycérol", "glycérine", "gliserol", "gliserin", "глицерин", "گلیسرول", "گلیسرین",
      "গ্লিসারল", "গ্লিসারিন", "甘油", "丙三醇", "گلیسیرین", "glicerol", "glicerina",
      "ग्लिसरॉल", "ग्लिसरीन", "glitserin", "ګلیسرول", "ګلیسرین", "glîserol", "glîserîn",
      "ഗ്ലിസറോൾ", "ഗ്ലിസറിൻ"
    ],
    i18nNames: {
      en: ["glycerol", "glycerin"],
      ar: ["جليسرول", "جليسرين"],
      fr: ["glycérol", "glycérine"],
      id: ["gliserol", "gliserin"],
      ru: ["глицерин"],
      ur: ["گلیسرول", "گلیسرین"],
      bn: ["গ্লিসারল", "গ্লিসারিন"],
      zh: ["甘油", "丙三醇"],
      fa: ["گلیسیرین"],
      es: ["glicerol", "glicerina"],
      hi: ["ग्लिसरॉल", "ग्लिसरीन"],
      uz: ["glitserin"],
      ps: ["ګلیسرول", "ګلیسرین"],
      ku: ["glîserol", "glîserîn"],
      ml: ["ഗ്ലിസറോൾ", "ഗ്ലിസറിൻ"]
    },
    status: HalalStatus.DOUBTFUL,
    reason: {
      ar: "غير محدد: قد يكون من مصادر نباتية (حلال) أو دهون حيوانية (مشبوه/حرام).",
      en: "Unspecified: Can be from plant sources (Halal) or animal fats (Doubtful/Haram).",
      fr: "Non spécifié : Peut provenir de sources végétales (Halal) ou de graisses animales (Douteux/Haram).",
      id: "Tidak ditentukan: Dapat berasal dari sumber nabati (Halal) atau lemak hewani (Meragukan/Haram).",
      tr: "Şüpheli: Bitkisel kaynaklardan (Helal) veya hayvansal yağlardan (Şüpheli/Haram) olabilir.",
      de: "Nicht spezifiziert: Kann aus pflanzlichen Quellen (Halal) oder tierischen Fetten (Zweifelhaft/Haram) stammen.",
      ru: "Сомнительно: Может быть из растительных источников (Халяль) или животных жиров (Сомнительно/Харам).",
      ur: "مشکوک: پودوں کے ذرائع (حلال) یا جانوروں کی چربی (مشکوک/حرام) سے ہو سکتا ہے۔",
      ms: "Tidak dinyatakan: Boleh daripada sumber tumbuhan (Halal) atau lemak haiwan (Diragui/Haram).",
      bn: "সন্দেহজনক: উদ্ভিদ উত্স (হালাল) বা পশুর চর্বি (সন্দেহজনক/হারাম) থেকে হতে পারে।",
      zh: "未指明：可能来自植物来源（Halal）或动物脂肪（存疑/Haram）。",
      fa: "مشکوک: می‌تواند از منابع گیاهی (حلال) یا چربی‌های حیوانی (مشکوک/حرام) باشد.",
      es: "No especificado: Puede ser de fuentes vegetales (Halal) o grasas animales (Dudoso/Haram).",
      hi: "संदिग्ध: पौधे के स्रोतों (हलाल) या पशु वसा (संदिग्ध/हराम) से हो सकता है।",
      uz: "Shubhali: O'simlik manbalaridan (Halol) yoki hayvon yog'laridan (Shubhali/Harom) bo'lishi mumkin.",
      kk: "Күмәнді: Өсімдік көздерінен (Халал) немесе жануарлар майларынан (Күмәнді/Харам) болуы мүмкін.",
      ky: "Күмөндүү: Өсүмдүк булактарынан (Адал) же жаныбарлардын майларынан (Күмөндүү/Арам) болушу мүмкүн.",
      so: "Shaki leh: Waxay ka imaan kartaa ilo dhirta (Xalaal) ama dufanka xoolaha (Shaki leh/Xaaraan).",
      ha: "Shakka: Ana iya samunsa daga tushen tsiro (Halal) ko kitsen dabbobi (Shakka/Haram).",
      sw: "Inatiliwa shaka: Inaweza kutokana na vyanzo vya mimea (Halali) au mafuta ya wanyama (Inatiliwa shaka/Haramu).",
      ps: "شکمن: کیدای شي د نباتاتو سرچینو (حلال) یا د څارویو غوړ (شکمن/حرام) څخه وي.",
      tl: "Kaduda-duda: Maaaring mula sa mga mapagkukunan ng halaman (Halal) o taba ng hayop (Kaduda-duda/Haram).",
      ku: "Gumanbar: Dibe ku ji çavkaniyên nebatan (Helal) an rûnên heywanan (Gumanbar/Heram) be.",
      ml: "സംശയാസ്പദമായത്: സസ്യ സ്രോതസ്സുകളിൽ നിന്നോ (ഹലാൽ) മൃഗങ്ങളുടെ കൊഴുപ്പിൽ നിന്നോ (സംശയാസ്പദമായ/ഹറാം) ആകാം."
    }
  },
  {
    id: "E472",
    names: [
      "e472", "e472a", "e472b", "e472c", "e472d", "e472e", "e472f", "esters of mono- and diglycerides", "إسترات أحادي وثنائي الجليسريدات",
      "esters de mono- et diglycérides", "ester mono- dan digliserida", "mono- ve digliseridlerin esterleri",
      "ester von mono- und diglyceriden", "эфиры моно- и диглицеридов", "مونو اور ڈائی گلیسرائڈز کے ایسٹرز",
      "মনো- এবং ডিগ্লিসারাইডসের এস্টার", "单甘油酯和双甘油酯的酯", "استرهای مونو و دی‌گلیسیرید",
      "ésteres de mono- y diglicéridos", "मोनो- और डिग्लिसराइड्स के एस्टर", "mono- va diglitseridlarning efirlari",
      "моно- және диглицеридтердің эфирлері", "моно- жана диглицериддердин эфирлери",
      "د مونو او ډای ګلیسریډز ایسټرونه", "esterên mono- û dîglîserîdan", "മോണോ- ആൻഡ് ഡൈഗ്ലിസറൈഡുകളുടെ എസ്റ്ററുകൾ"
    ],
    i18nNames: {
      en: ["esters of mono- and diglycerides"],
      ar: ["إسترات أحادي وثنائي الجليسريدات"],
      fr: ["esters de mono- et diglycérides"],
      id: ["ester mono- dan digliserida"],
      tr: ["mono- ve digliseridlerin esterleri"],
      de: ["ester von mono- und diglyceriden"],
      ru: ["эфиры моно- и диглицеридов"],
      ur: ["مونو اور ڈائی گلیسرائڈز کے ایسٹرز"],
      bn: ["মনো- এবং ডিগ্লিসারাইডসের এস্টার"],
      zh: ["单甘油酯和双甘油酯的酯"],
      fa: ["استرهای مونو و دی‌گلیسیرید"],
      es: ["ésteres de mono- y diglicéridos"],
      hi: ["मोनो- और डिग्लिसराइड्स के एस्टर"],
      uz: ["mono- va diglitseridlarning efirlari"],
      kk: ["моно- және диглицеридтердің эфирлері"],
      ky: ["моно- жана диглицериддердин эфирлери"],
      ps: ["د مونو او ډای ګلیسریډز ایسټرونه"],
      ku: ["esterên mono- û dîglîserîdan"],
      ml: ["മോണോ- ആൻഡ് ഡൈഗ്ലിസറൈഡുകളുടെ എസ്റ്ററുകൾ"]
    },
    status: HalalStatus.DOUBTFUL,
    reason: {
      ar: "غير محدد: مشتقات من E471، قد تكون من مصادر حيوانية أو نباتية.",
      en: "Unspecified: Derivatives of E471, can be from animal or plant sources.",
      fr: "Non spécifié : Dérivés de E471, peuvent provenir de sources animales ou végétales.",
      id: "Tidak ditentukan: Turunan dari E471, dapat berasal dari sumber hewani atau nabati.",
      tr: "Şüpheli: E471 türevleri, hayvansal veya bitkisel kaynaklı olabilir.",
      de: "Nicht spezifiziert: Derivate von E471, können aus tierischen oder pflanzlichen Quellen stammen.",
      ru: "Сомнительно: Производные E471, могут быть из животных или растительных источников.",
      ur: "مشکوک: E471 کے مشتقات، جانوروں یا پودوں کے ذرائع سے ہو سکتے ہیں۔",
      ms: "Tidak dinyatakan: Derivatif E471, boleh daripada sumber haiwan atau tumbuhan.",
      bn: "সন্দেহজনক: E471 এর ডেরিভেটিভস, প্রাণী বা উদ্ভিদ উত্স থেকে হতে পারে।",
      zh: "未指明：E471的衍生物，可能来自植物或动物来源。",
      fa: "مشکوک: مشتقات E471، می‌تواند از منابع حیوانی یا گیاهی باشد.",
      es: "No especificado: Derivados de E471, pueden ser de fuentes animales o vegetales.",
      hi: "संदिग्ध: E471 के डेरिवेटिव, पशु या पौधे के स्रोतों से हो सकते हैं।",
      uz: "Shubhali: E471 hosilalari, hayvon yoki o'simlik manbalaridan bo'lishi mumkin.",
      kk: "Күмәнді: E471 туындылары, жануарлар немесе өсімдік көздерінен болуы мүмкін.",
      ky: "Күмөндүү: E471 туундулары, жаныбарлар же өсүмдүк булактарынан болушу мүмкүн.",
      so: "Shaki leh: Waxyaabaha laga soo minguuriyay E471, waxay ka imaan karaan ilo xayawaan ama dhir.",
      ha: "Shakka: Abubuwan da suka samo asali daga E471, na iya zama daga tushen dabba ko tsiro.",
      sw: "Inatiliwa shaka: Viingilio vya E471, vinaweza kutokana na vyanzo vya wanyama au mimea.",
      ps: "شکمن: د E471 مشتقات، کیدای شي د څارویو یا نباتاتو سرچینو څخه وي.",
      tl: "Kaduda-duda: Mga derivatives ng E471, maaaring mula sa mga mapagkukunan ng hayop o halaman.",
      ku: "Gumanbar: Derîveyên E471, dibe ku ji çavkaniyên heywanan an nebatan be.",
      ml: "സംശയാസ്പദമായത്: E471 ൻ്റെ ഡെറിവേറ്റീവുകൾ, മൃഗങ്ങളിൽ നിന്നോ സസ്യ സ്രോതസ്സുകളിൽ നിന്നോ ആകാം."
    }
  },
  {
    id: "E481",
    names: [
      "e481", "sodium stearoyl-2-lactylate", "ستيرويل لاكتيلات الصوديوم",
      "stéaroyl-2-lactylate de sodium", "natrium stearoil-2-laktilat", "sodyum stearoil-2-laktilat",
      "natriumstearoyl-2-lactylat", "стеароил-2-лактилат натрия", "سوڈیم سٹیرول-2-لیکٹیلیٹ",
      "সোডিয়াম স্টিয়ারয়েল-২-ল্যাকটাইলেট", "硬脂酰乳酰乳酸钠", "سدیم استئارویل-۲-لاکتیلات",
      "estearoil-2-lactilato de sodio", "सोडियम स्टीयरॉयल-2-लैक्टिलेट", "natriy stearoil-2-laktilat",
      "натрий стеароил-2-лактилаты", "سوډیم سټیرول-2-لیکټیلیټ", "sodyûm stearoyl-2-lactylate",
      "സോഡിയം സ്റ്റിയറോയിൽ-2-ലാക്റ്റൈലേറ്റ്"
    ],
    i18nNames: {
      en: ["sodium stearoyl-2-lactylate"],
      ar: ["ستيرويل لاكتيلات الصوديوم"],
      fr: ["stéaroyl-2-lactylate de sodium"],
      id: ["natrium stearoil-2-laktilat"],
      tr: ["sodyum stearoil-2-laktilat"],
      de: ["natriumstearoyl-2-lactylat"],
      ru: ["стеароил-2-лактилат натрия"],
      ur: ["سوڈیم سٹیرول-2-لیکٹیلیٹ"],
      bn: ["সোডিয়াম স্টিয়ারয়েল-২-ল্যাকটাইলেট"],
      zh: ["硬脂酰乳酰乳酸钠"],
      fa: ["سدیم استئارویل-۲-لاکتیلات"],
      es: ["estearoil-2-lactilato de sodio"],
      hi: ["सोडियम स्टीयरॉयल-2-लैक्टिलेट"],
      uz: ["natriy stearoil-2-laktilat"],
      kk: ["натрий стеароил-2-лактилаты"],
      ps: ["سوډیم سټیرول-2-لیکټیلیټ"],
      ku: ["sodyûm stearoyl-2-lactylate"],
      ml: ["സോഡിയം സ്റ്റിയറോയിൽ-2-ലാക്റ്റൈലേറ്റ്"]
    },
    status: HalalStatus.DOUBTFUL,
    reason: {
      ar: "غير محدد: قد يحتوي على حمض الستياريك الذي قد يكون من مصدر حيواني.",
      en: "Unspecified: May contain stearic acid which can be of animal origin.",
      fr: "Non spécifié : Peut contenir de l'acide stéarique qui peut être d'origine animale.",
      id: "Tidak ditentukan: Mungkin mengandung asam stearat yang dapat berasal dari hewan.",
      tr: "Şüpheli: Hayvansal kökenli olabilen stearik asit içerebilir.",
      de: "Nicht spezifiziert: Kann Stearinsäure enthalten, die tierischen Ursprungs sein kann.",
      ru: "Сомнительно: Может содержать стеариновую кислоту, которая может быть животного происхождения.",
      ur: "مشکوک: اس میں سٹیرک ایسڈ ہو سکتا ہے جو جانوروں سے حاصل کیا جا سکتا ہے۔",
      ms: "Tidak dinyatakan: Mungkin mengandungi asid stearik yang boleh berasal daripada haiwan.",
      bn: "সন্দেহজনক: স্টিয়ারিক অ্যাসিড থাকতে পারে যা প্রাণীজ উত্সের হতে পারে।",
      zh: "未指明：可能含有硬脂酸，硬脂酸可能源自动物。",
      fa: "مشکوک: ممکن است حاوی اسید استئاریک باشد که می‌تواند منشأ حیوانی داشته باشد.",
      es: "No especificado: Puede contener ácido esteárico que puede ser de origen animal.",
      hi: "संदिग्ध: इसमें स्टीयरिक एसिड हो सकता है जो पशु मूल का हो सकता है।",
      uz: "Shubhali: Hayvon kelib chiqishi mumkin bo'lgan stearin kislotasini o'z ichiga olishi mumkin.",
      kk: "Күмәнді: Құрамында жануардан алынатын стеарин қышқылы болуы мүмкін.",
      ky: "Күмөндүү: Курамында жаныбардан алынган стеарин кислотасы болушу мүмкүн.",
      so: "Shaki leh: Waxaa laga yaabaa inay ku jirto stearic acid taas oo noqon karta asal xayawaan.",
      ha: "Shakka: Yana iya ƙunsar stearic acid wanda zai iya zama asalin dabba.",
      sw: "Inatiliwa shaka: Inaweza kuwa na asidi ya stearic ambayo inaweza kuwa ya asili ya wanyama.",
      ps: "شکمن: کیدای شي سټیریک اسید ولري چې کیدای شي د څارویو اصلي وي.",
      tl: "Kaduda-duda: Maaaring maglaman ng stearic acid na maaaring nagmula sa hayop.",
      ku: "Gumanbar: Dibe ku asîda stearîk hebe ku dibe ku bi eslê xwe heywanî be.",
      ml: "സംശയാസ്പദമായത്: മൃഗങ്ങളിൽ നിന്നുള്ള സ്റ്റിയറിക് ആസിഡ് അടങ്ങിയിരിക്കാം."
    }
  },
  {
    id: "E621",
    names: [
      "e621", "msg", "monosodium glutamate", "غلوتامات أحادية الصوديوم",
      "glutamate monosodique", "gms", "mononatrium glutamat", "vetsin", "monosodyum glutamat",
      "mononatriumglutamat", "глутамат натрия", "مونوسوڈیم گلوٹامیٹ", "মনোসোডিয়াম গ্লুটামেট",
      "谷氨酸钠", "味精", "مونوسدیم گلوتامات", "glutamato monosódico", "मोनोसोडियम ग्लूटामेट",
      "monosodyum glutamat", "натрий глутаматы", "مونوسوډیم ګلوټامیټ", "monosodyûm glûtaat",
      "മോണോസോഡിയം ഗ്ലൂട്ടാമേറ്റ്"
    ],
    i18nNames: {
      en: ["msg", "monosodium glutamate"],
      ar: ["غلوتامات أحادية الصوديوم"],
      fr: ["glutamate monosodique", "gms"],
      id: ["mononatrium glutamat", "vetsin"],
      tr: ["monosodyum glutamat"],
      de: ["mononatriumglutamat"],
      ru: ["глутамат натрия"],
      ur: ["مونوسوڈیم گلوٹامیٹ"],
      bn: ["মনোসোডিয়াম গ্লুটামেট"],
      zh: ["谷氨酸钠", "味精"],
      fa: ["مونوسدیم گلوتامات"],
      es: ["glutamato monosódico"],
      hi: ["मोनोसोडियम ग्लूटामेट"],
      uz: ["monosodyum glutamat"],
      kk: ["натрий глутаматы"],
      ps: ["مونوسوډیم ګلوټامیټ"],
      ku: ["monosodyûm glûtaat"],
      ml: ["മോണോസോഡിയം ഗ്ലൂട്ടാമേറ്റ്"]
    },
    status: HalalStatus.HALAL,
    reason: {
      ar: "مسموح: معزز نكهة يصنع عادة من تخمير النشا أو قصب السكر.",
      en: "Permissible: Flavor enhancer usually made from fermenting starch or sugar cane.",
      fr: "Permissible : Exhausteur de goût généralement fabriqué par fermentation d'amidon ou de canne à sucre.",
      id: "Permissible: Penguat rasa yang biasanya dibuat dari fermentasi pati atau tebu.",
      tr: "Helal: Genellikle nişasta veya şeker kamışının fermantasyonundan yapılan lezzet arttırıcı.",
      de: "Permissible: Geschmacksverstärker, der normalerweise durch Fermentation von Stärke oder Zuckerrohr hergestellt wird.",
      ru: "Халяль: Усилитель вкуса, обычно изготавливаемый путем ферментации крахмала или сахарного тростника.",
      ur: "مسموح: ذائقہ بڑھانے والا عام طور پر نشاستہ یا گنے کو خمیر کرکے بنایا جاتا ہے۔",
      ms: "Permissible: Penambah perisa yang biasanya dibuat daripada penapaian kanji atau tebu.",
      bn: "হালাল: স্বাদ বর্ধক সাধারণত স্টার্চ বা আখ গাঁজন থেকে তৈরি হয়。",
      zh: "清真：增味剂，通常由发酵淀粉或甘蔗制成。",
      fa: "مسموح: تقویت کننده طعم که معمولاً از تخمیر نشاسته یا نیشکر ساخته می‌شود.",
      es: "Permissible: Potenciador del sabor generalmente hecho de la fermentación de almidón o caña de azúcar.",
      hi: "हलाल: स्वाद बढ़ाने वाला आमतौर पर स्टार्च या गन्ने को किण्वित करके बनाया जाता है。",
      uz: "Halol: Odatda kraxmal yoki shakarqamishni achitish orqali tayyorlanadigan lazzat kuchaytirgich.",
      kk: "Халал: Әдетте крахмал немесе қант қамысын ашыту арқылы жасалатын дәм күшейткіш.",
      ky: "Адал: Адатта крахмал же кант камышын ачытуу жолу менен жасалган даам күчөткүч.",
      so: "Xalaal: Kobciyaha dhadhanka oo inta badan laga sameeyo istaarijka khamiirsan ama bakooradda sonkorta.",
      ha: "Permissible: Mai haɓaka ɗanɗano wanda aka saba yi daga sitaci ko rake.",
      sw: "Halali: Kiboresha ladha ambacho kwa kawaida hutengenezwa kwa kuchachusha wanga au miwa.",
      ps: "مسموح: د خوند لوړونکی معمولا د نشایسته یا ګني د خمیر کولو څخه جوړیږي.",
      tl: "Permissible: Pampalasa na karaniwang ginagawa mula sa pagbuburo ng almirol o tubo.",
      ku: "Helal: Zêdekera tamê ku bi gelemperî ji fermentasyona nîşa an kaniya şekir tê çêkirin.",
      ml: "ഹലാൽ: അന്നജം അല്ലെങ്കിൽ കരിമ്പ് പുളിപ്പിച്ച് സാധാരണയായി ഉണ്ടാക്കുന്ന ഫ്ലേവർ എൻഹാൻസർ."
    }
  }
];

export const checkLocalDatabase = (text: string, language: string = 'ar'): { status: HalalStatus; detected: IngredientDetail[], reason: string } | null => {
  const lowerText = text.toLowerCase();
  const detected: IngredientDetail[] = [];
  let finalStatus = HalalStatus.HALAL;
  const reasons: string[] = [];

  OFFLINE_DB.forEach(item => {
    // Check if any of the names exist in the text
    const found = item.names.some(name => lowerText.includes(name.toLowerCase()));

    if (found) {
      detected.push({
        name: item.id,
        status: item.status
      });

      const reasonText = item.reason[language] || item.reason['en'] || item.reason['ar'];
      reasons.push(`- ${item.id}: ${reasonText}`);

      // Update final status (HARAM overrides DOUBTFUL)
      if (item.status === HalalStatus.HARAM) {
        finalStatus = HalalStatus.HARAM;
      } else if (item.status === HalalStatus.DOUBTFUL && finalStatus !== HalalStatus.HARAM) {
        finalStatus = HalalStatus.DOUBTFUL;
      }
    }
  });

  if (detected.length > 0) {
    return {
      status: finalStatus,
      detected,
      reason: reasons.join('\n\n')
    };
  }

  return null;
};

// Keep the old function for backward compatibility in geminiService.ts fast-path
export const checkLocalHaram = (text: string): { status: HalalStatus; detected: IngredientDetail[] } | null => {
  const result = checkLocalDatabase(text, 'en');
  if (result && result.status === HalalStatus.HARAM) {
    return { status: result.status, detected: result.detected };
  }
  return null;
};
