
name: Build Android APK

on:
  # Trigger only manually via GitHub Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Make Scripts Executable
        run: chmod +x scripts/*.js

      # Explicit step to generate keys before build starts
      - name: Generate Keystore & SHA-1
        run: npm run get-sha1

      # IMPORTANT: Pass Secrets to the build command so Vite can bake them into the APK
      - name: Build APK
        run: npm run build-apk
        env:
          CI: true
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}

      - name: Upload APK and SHA-1 Info
        if: always() # Upload artifacts even if build fails (useful for debugging signing)
        uses: actions/upload-artifact@v4
        with:
          name: HalalScanner-Build-Artifacts
          path: |
            android/app/build/outputs/apk/debug/app-debug.apk
            sha1_fingerprint.txt
            debug.keystore
          retention-days: 5
